Feat/review changes
raghul1212/springboot_interviewmanagement pull request #2
Opened 2021-09-20 06:28 UTC by raghul1212

2021-09-22 14:40 UTC, abySebastin95 requested changes

2021-09-22 14:40 UTC, abySebastin95 commented on MYSQL scripts/interviewmanagementhibernate.sql
> +use sample;
Using DB name is not advisable.

2021-09-22 14:40 UTC, abySebastin95 commented on MYSQL scripts/interviewmanagementhibernate.sql
> +use sample;
Using the DB name is not advisable.

2021-09-22 14:40 UTC, abySebastin95 commented on MYSQL scripts/interviewmanagementhibernate.sql
> +    CREATE PROCEDURE getCandidateUpdateByEmail(in email varchar(30),in id bigint)
in id bigint - id means ?? Not meaning full

2021-09-22 14:40 UTC, abySebastin95 commented on MYSQL scripts/interviewmanagementhibernate.sql
> +use sample;
Log files -
${basePath}/application.log - This should not be pushed to github.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/CandidateDao.java
> +	public String addCandidate(Long id,CandidateDto candidate);
We can have the ID inside the DTO itself, why in separate params!!

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/EmployeeCredentialDao.java
> +	public String updatePassword(Long id, EmployeeCredentialDto employeeCredential);
Why separate param, if we are passing the whole DTO. !!

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/EmployeeDao.java
> +	public String addEmployee(Long id,EmployeeDto employee);
Why separate param, if we are passing the whole dto.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/RecoveryPasswordDao.java
> +	public void addCode(RecoveryPasswordDto recoverPassword, String forgotPasswordCode);
Why separate param, if we are passing the whole dto.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/ResultDao.java
> +public interface ResultDao {
By Default Interface has PUBLIC ACCESS MODIFIERS. We don't need to mention it here.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/impl/CandidateCredentialDaoImpl.java
> +	private static final Logger logger=LogManager.getLogger(CandidateCredentialDaoImpl.class.getName());
.get name is not necessary. 
ex: 
    private static final Logger logger = LogManager.getLogger(RevProServiceImp.class);

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/impl/CandidateCredentialDaoImpl.java
> +		@SuppressWarnings("unchecked")
Not advisable to use - Suppress warnings.
Need to be checked and fixed.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/impl/CandidateCredentialDaoImpl.java
> +		return (resultList.isEmpty()?null:resultList.get(0));
get(0) !!

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/impl/CandidateCredentialDaoImpl.java
> +		Session session=sessionFactory.getCurrentSession();
This line is getting duplicated !!

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/impl/CandidateCredentialDaoImpl.java
> +			Long id=(Long) session.save(candidateCredential);
Type casting is not advisable.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/impl/CandidateCredentialDaoImpl.java
> +			return "Candidate credentials created successfully with id "+id+" !";
return "Candidate credentials created successfully with id "+id+" !";
All these msg's can be moved to one Properties or Constant File - Common constant file.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/impl/CandidateCredentialDaoImpl.java
> +			throw new DuplicateIdException("Entered Email id already exists in another record");
Msg to Constant file.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/impl/CandidateCredentialDaoImpl.java
> +		catch (org.hibernate.ObjectNotFoundException e1) {
Not the right way to catch the exp.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/dao/impl/CandidateCredentialDaoImpl.java
> +		return !resultList.isEmpty();
Not right way to return as response.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/entity/Result.java
> +	@JoinColumn(nullable=false)
@JoinColumn(nullable=false)
 purpose of nullable  ??!!

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/entity/credentials/CandidateCredential.java
> +	@OneToOne(mappedBy="candidateCredential",cascade=CascadeType.ALL)
why cascadetype is all

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/rest/CandidateCredentialController.java
> +@RequestMapping("/api")
/ api is not the right word here.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/rest/CandidateCredentialController.java
> +@CrossOrigin("http://localhost:4200")
this has to be domain-specific or *

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/rest/CandidateCredentialController.java
> +	 @PutMapping("/candidate/credential/resend-code")
resend-code is not advisable - Not more than one word in mapping.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/rest/CandidateCredentialController.java
> +	 @PutMapping("/candidate/credential/reset-password")
/candidate can be moved to request mapping in the Top. 
/api should be removed.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/rest/ResultController.java
> + @ExceptionHandler(IdNotFoundException.class)
The controller should not have these.

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/service/impl/CandidateCredentialServiceImpl.java
> +	private CandidateCredentialDao candidateCredentialDao ;
Extra space in between ;

2021-09-22 14:40 UTC, abySebastin95 commented on src/main/java/com/revature/interviewmanagement/service/impl/InterviewServiceImpl.java
> +@Service
Why do impl has @Service

2021-09-22 16:05 UTC, raghul1212 commented on MYSQL scripts/interviewmanagementhibernate.sql
> +    CREATE PROCEDURE getCandidateUpdateByEmail(in email varchar(30),in id bigint)
Long datatype in entity is mapped as bigint in database

2021-09-23 01:52 UTC, raghul1212 commented on src/main/java/com/revature/interviewmanagement/dao/EmployeeDao.java
> +	public String addEmployee(Long id,EmployeeDto employee);
Here, id refers to credential id of the employee which was created earlier and will be mapped to employee details entity.

2023-11-14 10:02 UTC, merged